site:
  title: Antora Tracer — Self-Traceability Example
  url: https://antora-tracer.conemso.de/docs
  start_page: tracer::index.adoc
  keys:
    annotatejs: opt-out

content:
  sources:
    - url: https://github.com/rattermeyer/antora-tracer.git
      start_path: examples/tracer
      branches: ['main', 'v0.23.x', 'v0.22.x']
    - url: https://github.com/rattermeyer/antora-tracer.git
      start_path: examples/demo
      branches: ['main']
    - url: https://github.com/rattermeyer/antora-tracer.git
      start_path: blog
      branches: ['main']

asciidoc:
  extensions:
    - asciidoctor-kroki

antora:
  extensions:
    - require: ./lib/src/antora-extension.js
      configPath: ./examples/traceability.yml
      outputDir: traceability
      generateMatrices: true
      matrixFormats: [html, csv]
      includeInNavigation: true
    - require: '@antora/lunr-extension'
      index_by_heading: true
    - require: ./lib/src/antora-vale-extension.js
      enabled: true
      valeConfig: lib/src/vale/.vale.ini
      minLevel: warning
      exclude:
        - documentation-style-guide.adoc

ui:
  bundle:
    url: https://github.com/rattermeyer/antora-ui-conemso/releases/download/v1.1.3/ui-bundle.zip
  supplemental_files: ./examples/ui-supplemental

urls:
  latest_version_segment: stable
  redirect_facility: static


output:
  dir: ./public/docs
  clean: true
