site:
  title: Antora Tracer — Self-Traceability Example (PDF)
  url: https://antora-tracer.conemso.de/docs
  start_page: tracer::index.adoc

content:
  sources:
    - url: .
      start_path: examples/tracer
      branches: HEAD

asciidoc:
  attributes:
    pdf-theme: default
    kroki-default-format: png
  extensions:
    - asciidoctor-kroki

antora:
  extensions:
    - require: ./lib/src/antora-extension.js
      preset: self-traceability
      configPath: ./examples/traceability.yml
      outputDir: traceability
      generateMatrices: true
      matrixFormats: [html, csv]
      includeInNavigation: true
    - require: ./lib/src/antora-pdf-extension.cjs
      config_files:
        - examples/antora-assembler-pdf.yml
        - examples/antora-assembler-pdf-architecture.yml
        - examples/antora-assembler-pdf-use-cases.yml
        - examples/antora-assembler-pdf-requirements.yml
        - examples/antora-assembler-pdf-test-plan.yml
    - require: ./lib/src/antora-docx-extension.cjs
      config_files:
        - examples/antora-assembler-docx.yml
        - examples/antora-assembler-docx-architecture.yml
        - examples/antora-assembler-docx-requirements.yml
        - examples/antora-assembler-docx-use-cases.yml
        - examples/antora-assembler-docx-test-plan.yml

output:
  dir: ./build/pdf-output
  clean: true

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
