/**
 * Neo4j Exporter for traceability graphs
 * Exports traceability data in CSV or Cypher format for import into Neo4j
 */
import * as fs from "node:fs";
import * as path from "node:path";
import { itemIdentity } from "./types.js";
/**
 * Neo4jExporter - Exports traceability graphs to Neo4j format
 *
 * Supports both CSV and Cypher export formats.
 * CSV format produces nodes.csv and relationships.csv files.
 * Cypher format produces import.cypher file with MERGE statements.
 */
export class Neo4jExporter {
    graph;
    constructor(graph) {
        this.graph = graph;
    }
    /**
     * Export the graph to Neo4j format
     */
    export(options) {
        const outputDir = options.outputDir;
        const format = options.format;
        const includeContent = options.includeContent ?? true;
        const includeAllAttributes = options.includeAllAttributes ?? true;
        // Ensure output directory exists
        if (!fs.existsSync(outputDir)) {
            fs.mkdirSync(outputDir, { recursive: true });
        }
        const items = this.graph.getAllItems();
        const relationships = this.graph.getAllRelationships();
        const result = {
            nodeCount: items.length,
            relationshipCount: relationships.length,
        };
        if (format === "csv") {
            // Export to CSV format
            const nodesFile = path.resolve(outputDir, "nodes.csv");
            const relationshipsFile = path.resolve(outputDir, "relationships.csv");
            this.exportNodesToCSV(items, nodesFile, includeContent, includeAllAttributes);
            this.exportRelationshipsToCSV(relationships, relationshipsFile);
            result.nodesFile = nodesFile;
            result.relationshipsFile = relationshipsFile;
        }
        else {
            // Export to Cypher format
            const cypherFile = path.resolve(outputDir, "import.cypher");
            this.exportToCypher(items, relationships, cypherFile, includeContent, includeAllAttributes);
            result.cypherFile = cypherFile;
        }
        return result;
    }
    /**
     * Export nodes to CSV format
     */
    exportNodesToCSV(items, filePath, includeContent, includeAllAttributes) {
        const headers = ["id", "identity", "component", "version", "title", "role", "status", "sourceFile"];
        const attributeKeys = [];
        // Collect all attribute keys if including all attributes
        if (includeAllAttributes) {
            for (const item of items) {
                for (const key of Object.keys(item.attributes || {})) {
                    if (!attributeKeys.includes(key)) {
                        attributeKeys.push(key);
                    }
                }
            }
            headers.push(...attributeKeys);
        }
        if (includeContent) {
            headers.push("content");
        }
        const lines = [this.escapeCSVRow(headers)];
        for (const item of items) {
            const row = [
                item.id,
                itemIdentity(item),
                item.component || "",
                item.version || "",
                this.escapeCSVValue(item.title || ""),
                item.role,
                item.status || "",
                item.sourceFile || "",
            ];
            if (includeAllAttributes) {
                for (const key of attributeKeys) {
                    row.push(this.escapeCSVValue(item.attributes?.[key] || ""));
                }
            }
            if (includeContent) {
                row.push(this.escapeCSVValue(item.content || ""));
            }
            lines.push(this.escapeCSVRow(row));
        }
        fs.writeFileSync(filePath, lines.join("\n"), "utf8");
    }
    /**
     * Export relationships to CSV format
     */
    exportRelationshipsToCSV(relationships, filePath) {
        const headers = [
            "id",
            "source",
            "target",
            "sourceId",
            "targetId",
            "type",
            "sourceFile",
            "bidirectional",
        ];
        const lines = [this.escapeCSVRow(headers)];
        for (const rel of relationships) {
            const row = [
                rel.id,
                rel.fromIdentity || rel.fromId,
                rel.targetIdentity || rel.targetId,
                rel.fromId,
                rel.targetId,
                rel.type,
                rel.sourceFile || "",
                rel.bidirectional ? "true" : "false",
            ];
            lines.push(this.escapeCSVRow(row));
        }
        fs.writeFileSync(filePath, lines.join("\n"), "utf8");
    }
    /**
     * Export to Cypher format
     */
    exportToCypher(items, relationships, filePath, includeContent, includeAllAttributes) {
        const lines = [
            "// Neo4j Cypher import file",
            "// Generated by antora-requirements-traceability",
            "// Use: neo4j-admin import --nodes=import.cypher --relationships=import.cypher",
            "",
        ];
        // Add node creation statements
        for (const item of items) {
            const props = {
                id: item.id,
                identity: itemIdentity(item),
                component: item.component || "",
                version: item.version || "",
                title: item.title || "",
                role: item.role,
            };
            if (item.status) {
                props.status = item.status;
            }
            if (item.sourceFile) {
                props.sourceFile = item.sourceFile;
            }
            if (includeContent && item.content) {
                props.content = item.content;
            }
            if (includeAllAttributes) {
                for (const [key, value] of Object.entries(item.attributes || {})) {
                    props[key] = value;
                }
            }
            const escapedIdentity = { ...props, identity: itemIdentity(item) };
            const escapedProps = this.formatCypherProperties(escapedIdentity);
            lines.push(`MERGE (n:Item {identity: ${this.formatCypherValue(itemIdentity(item))}}) SET n += ${escapedProps};`);
            lines.push("");
        }
        // Add relationship creation statements
        for (const rel of relationships) {
            const props = {
                id: rel.id,
                type: rel.type,
            };
            if (rel.sourceFile) {
                props.sourceFile = rel.sourceFile;
            }
            if (rel.bidirectional) {
                props.bidirectional = "true";
            }
            const propsStr = this.formatCypherProperties(props);
            lines.push(`MATCH (source:Item {identity: ${this.formatCypherValue(rel.fromIdentity || rel.fromId)}}), (target:Item {identity: ${this.formatCypherValue(rel.targetIdentity || rel.targetId)}}) ` +
                `MERGE (source)-[r:RELATIONSHIP ${propsStr}]->(target);`);
            lines.push("");
        }
        // Add indexes for better performance
        lines.push("// Indexes");
        lines.push("CREATE INDEX IF NOT EXISTS FOR (n:Item) ON (n.identity);");
        lines.push("CREATE INDEX IF NOT EXISTS FOR (n:Item) ON (n.role);");
        lines.push("");
        fs.writeFileSync(filePath, lines.join("\n"), "utf8");
    }
    /**
     * Escape a value for CSV
     */
    escapeCSVValue(value) {
        if (value === undefined || value === null) {
            return "";
        }
        const str = String(value);
        // If the value contains commas, quotes, or newlines, wrap in quotes and escape quotes
        if (str.includes(",") ||
            str.includes('"') ||
            str.includes("\n") ||
            str.includes("\r")) {
            return `"${str.replace(/"/g, '""')}"`;
        }
        return str;
    }
    /**
     * Escape a row for CSV (array of values)
     */
    escapeCSVRow(row) {
        return row.map((v) => this.escapeCSVValue(v)).join(",");
    }
    formatCypherValue(value) {
        const escaped = value.replace(/\\/g, "\\\\").replace(/'/g, "\\'");
        return `'${escaped.replace(/\u0000/g, "\\u0000")}'`;
    }
    /**
     * Format properties for Cypher
     */
    formatCypherProperties(props) {
        const parts = [];
        for (const [key, value] of Object.entries(props)) {
            // Escape quotes in string values
            parts.push(`${key}: ${this.formatCypherValue(value)}`);
        }
        return `{${parts.join(", ")}}`;
    }
}
