site:
  title: Antora Requirements Traceability Extension
  start_page: ROOT::index.adoc
  url: https://example.com

content:
  sources:
    - url: .
      branches: HEAD
      start_path: docs

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true

antora:
  extensions:
    - import: ../lib/src/antora-extension.js

output:
  clean: true
  dir: ./_site
