#!/usr/bin/env node
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
/**
 * Self-traceability example runner
 * Processes all example files together, validates them, and exports the Neo4j CSV
 *
 * Usage: node examples/run-example.js
 */
import {
  ConfigLoader,
  RequirementsTraceabilityExtension,
} from "../lib/src/index.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const pagesDir = resolve(__dirname, "tracer/modules/ROOT/pages");
const outputDir = resolve(__dirname, "tracer/modules/ROOT/attachments/traceability");

// Load custom config
const configLoader = new ConfigLoader();
configLoader.load(resolve(__dirname, "traceability.yml"));

// Process all example files
const extension = new RequirementsTraceabilityExtension(configLoader);
const files = [
  "self-traceability/use-cases.adoc",
  { adoc: "requirements.adoc", realPath: resolve(__dirname, "tracer/modules/requirements/pages/index.adoc") },
  { adoc: "demo/index.adoc", realPath: resolve(__dirname, "demo/modules/ROOT/pages/index.adoc") },
  "explanation/architecture.adoc", "self-traceability/test-plan.adoc", "self-traceability/delivery-process.adoc",
  "explanation/quality/zero-operational-overhead.adoc", "explanation/quality/configurable-without-code.adoc",
  "explanation/quality/fail-fast-diagnostics.adoc", "explanation/quality/no-side-effects.adoc",
  "explanation/quality/testability-by-design.adoc", "explanation/quality/pdf-compatibility.adoc",
  "explanation/quality/platform-stability.adoc", "explanation/quality/performance.adoc"
];
const results = extension.processFiles(
  files.map((f) => {
    if (typeof f === "string") {
      return { path: f, content: readFileSync(resolve(pagesDir, f), "utf8") };
    }
    return { path: f.adoc, content: readFileSync(f.realPath, "utf8") };
  }),
);

// Print summary
console.log(`\nProcessed ${files.length} files:`);
for (const r of results.fileResults) {
  console.log(
    `  ${r.file}: ${r.items} items, ${r.relationships} relationships`,
  );
}
console.log(
  `\nTotal: ${results.result.items.length} items, ${results.result.relationships.length} relationships`,
);

// Role statistics
const stats = extension.getRoleStatistics();
console.log("\nItems by role:");
for (const [role, count] of Object.entries(stats)) {
  console.log(`  ${role}: ${count}`);
}

// Validation
const validation = extension.validate();
console.log(
  `\nValidation: ${validation.errors.length} errors, ${validation.warnings.length} warnings`,
);

// Generate Neo4j export (matrices are generated by the extension at build time)
const { Neo4jExporter } = await import("../lib/src/Neo4jExporter.js");

mkdirSync(outputDir, { recursive: true });

// Neo4j
const neo4j = new Neo4jExporter(extension.graph);
const neo4jResult = neo4j.export({
  outputDir,
  format: "csv",
  includeContent: true,
  includeAllAttributes: true,
});
console.log(
  `Neo4j CSV: ${neo4jResult.nodeCount} nodes, ${neo4jResult.relationshipCount} relationships`,
);
