users:
  demo:
    disabled: false
    displayname: 'Demo User'
    password: '$argon2id$v=19$m=65536,t=3,p=4$Vpy8BoyFsXKsT7cC2zLM/w$IistnmWo/M8FVmkDgljh5EjziRy3jZKg0MbZWWeW8Zw'
    email: 'demo@example.com'
