// Shared types and interfaces for requirements traceability

export interface TraceableNode {
  id: string;
  title: string;
  content?: string;
  status?: string;
  attributes?: Record<string, string>;
  sourceFile?: string;
  sourceLine?: number;
}

export interface Requirement extends TraceableNode {
  content: string;
  status: string;
  attributes: Record<string, string>;
  sourceFile: string;
  sourceLine: number;
}

export interface Implementation extends TraceableNode {}
export interface Test extends TraceableNode {}
export interface Document extends TraceableNode {}
export interface Design extends TraceableNode {}

export type AnyNode = Requirement | Implementation | Test | Document | Design;

export type RelationshipType =
  | 'implements'
  | 'satisfies'
  | 'tests'
  | 'verifies'
  | 'documents'
  | 'depends'
  | 'requires'
  | 'addresses'
  | 'composed-of'
  | 'depends-on'
  | 'implemented-by'
  | 'satisfied-by'
  | 'tested-by'
  | 'verified-by'
  | 'documented-by'
  | 'depended-by'
  | 'required-by'
  | 'addressed-by'
  | 'part-of'
  | 'depends-on-by';

// Primary relationship types (user-defined)
export type PrimaryRelationshipType =
  | 'implements'
  | 'satisfies'
  | 'tests'
  | 'verifies'
  | 'documents'
  | 'depends'
  | 'requires'
  | 'addresses'
  | 'composed-of'
  | 'depends-on';

// Inverse relationship types (auto-generated)
export type InverseRelationshipType =
  | 'implemented-by'
  | 'satisfied-by'
  | 'tested-by'
  | 'verified-by'
  | 'documented-by'
  | 'depended-by'
  | 'required-by'
  | 'addressed-by'
  | 'part-of'
  | 'depends-on-by';

// Mapping constants for bidirectional relationships
export const INVERSE_MAP: Record<PrimaryRelationshipType, InverseRelationshipType> = {
  'implements': 'implemented-by',
  'satisfies': 'satisfied-by',
  'tests': 'tested-by',
  'verifies': 'verified-by',
  'documents': 'documented-by',
  'depends': 'depended-by',
  'requires': 'required-by',
  'addresses': 'addressed-by',
  'composed-of': 'part-of',
  'depends-on': 'depends-on-by',
};

export const PRIMARY_MAP: Record<InverseRelationshipType, PrimaryRelationshipType> = {
  'implemented-by': 'implements',
  'satisfied-by': 'satisfies',
  'tested-by': 'tests',
  'verified-by': 'verifies',
  'documented-by': 'documents',
  'depended-by': 'depends',
  'required-by': 'requires',
  'addressed-by': 'addresses',
  'part-of': 'composed-of',
  'depends-on-by': 'depends-on',
} as const;

export interface Relationship {
  id: string;
  fromId: string;
  targetId: string;
  type: RelationshipType;
  sourceFile?: string;
  line?: number;
  autoGenerated?: boolean;
  inverseOf?: string;
}

export interface CoverageReport {
  totalRequirements: number;
  requirementsWithImplementation: number;
  requirementsWithTests: number;
  implementationCoverage: number;
  testCoverage: number;
  // Design coverage metrics
  totalDesigns: number;
  designsWithImplementation: number;
  designCoverage: number;
  requirementsAddressedByDesign: number;
  requirementCoverageByDesign: number;
}

export interface RequirementRow {
  id: string;
  title: string;
  implementations: string[];
  tests: string[];
}

export interface DesignRow {
  id: string;
  title: string;
  implementations: string[];
  tests: string[];
  depth?: number; // For visual hierarchy in design-design matrix
}

export interface RequirementDetail {
  id: string;
  title: string;
  status: string;
  satisfiedBy: string[];
  implementedBy: string[];
  testedBy: string[];
  verifiedBy: string[];
  documentedBy: string[];
}

export interface ImplementationDetail {
  id: string;
  title: string;
  satisfies: string[];
  testedBy: string[];
}

export interface TestDetail {
  id: string;
  title: string;
  verifies: string[];
  tests: string[];
}

export interface TraceabilityMatrix {
  type: string;
  coverage: CoverageReport;
  requirements: RequirementRow[];
  generatedAt: string;
}

export interface DesignTraceabilityMatrix {
  type: string;
  coverage: CoverageReport;
  designs: DesignRow[];
  generatedAt: string;
}

export interface DetailedTraceabilityMatrix {
  type: string;
  coverage: CoverageReport;
  uncoveredRequirements: string[];
  requirements: RequirementDetail[];
  implementations: ImplementationDetail[];
  tests: TestDetail[];
  generatedAt: string;
}

export interface ProcessOptions {
  sourceFile?: string;
}

// Type guards for relationship types
export function isPrimaryRelationshipType(type: string): type is PrimaryRelationshipType {
  return type in INVERSE_MAP;
}

export function isInverseRelationshipType(type: string): type is InverseRelationshipType {
  return type in PRIMARY_MAP;
}
