/**
 * Type definitions for unified item architecture
 * This file contains the types for requirements traceability
 */

// ============================================================================
// Core Item Type
// ============================================================================

/**
 * Base type for all traceable items
 * Replaces Requirement, Implementation, Test, Document, Design
 */
export interface Item {
  id: string;
  title: string;
  content?: string;
  role: string; // User-defined role (requirement, design, test, etc.)
  status?: string;
  attributes: Record<string, string>;
  sourceFile?: string;
  sourceLine?: number;
  /** Antora component name (e.g., "tracer"). Absent for CLI usage. */
  component?: string;
  /** Antora module name (e.g., "ROOT", "requirements"). Absent for CLI usage. */
  module?: string;
}

/**
 * Relationship between items with role information
 */
export interface ItemRelationship {
  id: string;
  fromId: string;
  targetId: string;
  type: string; // User-defined relation type
  sourceFile?: string;
  line?: number;
  autoGenerated?: boolean;
  inverseOf?: string;
}

// ============================================================================
// Backward Compatibility Types
// ============================================================================

/**
 * Legacy types for backward compatibility
 * These will be deprecated
 */
export interface Requirement {
  id: string;
  title: string;
  content: string;
  status: string;
  attributes: Record<string, string>;
  sourceFile: string;
  sourceLine: number;
}

export interface Implementation {
  id: string;
  title: string;
  content?: string;
  status?: string;
  attributes?: Record<string, string>;
  sourceFile?: string;
  sourceLine?: number;
}

export interface Test {
  id: string;
  title: string;
  content?: string;
  status?: string;
  attributes?: Record<string, string>;
  sourceFile?: string;
  sourceLine?: number;
}

export interface Document {
  id: string;
  title: string;
  content?: string;
  status?: string;
  attributes?: Record<string, string>;
  sourceFile?: string;
  sourceLine?: number;
}

export interface Design {
  id: string;
  title: string;
  content?: string;
  status?: string;
  attributes?: Record<string, string>;
  sourceFile?: string;
  sourceLine?: number;
}

/**
 * Union type for all node types (legacy)
 */
export type AnyNode = Requirement | Implementation | Test | Document | Design;

/**
 * Legacy relationship types
 */
export type RelationshipType =
  | "implements"
  | "satisfies"
  | "tests"
  | "verifies"
  | "documents"
  | "depends"
  | "requires"
  | "addresses"
  | "composed-of"
  | "depends-on"
  | "implemented-by"
  | "satisfied-by"
  | "tested-by"
  | "verified-by"
  | "documented-by"
  | "depended-by"
  | "required-by"
  | "addressed-by"
  | "part-of"
  | "is-a-dependency-of";

export type PrimaryRelationshipType =
  | "implements"
  | "satisfies"
  | "tests"
  | "verifies"
  | "documents"
  | "depends"
  | "requires"
  | "addresses"
  | "composed-of"
  | "depends-on"
  | "refines"
  | "leads-to";

export type InverseRelationshipType =
  | "implemented-by"
  | "satisfied-by"
  | "tested-by"
  | "verified-by"
  | "documented-by"
  | "depended-by"
  | "required-by"
  | "addressed-by"
  | "part-of"
  | "is-a-dependency-of"
  | "refined-by"
  | "led-by";

/**
 * Legacy relationship interface
 */
export interface Relationship {
  id: string;
  fromId: string;
  targetId: string;
  type: RelationshipType;
  sourceFile?: string;
  line?: number;
  autoGenerated?: boolean;
  inverseOf?: string;
}

/**
 * Mapping constants for bidirectional relationships (legacy)
 */
export const INVERSE_MAP: Record<
  PrimaryRelationshipType,
  InverseRelationshipType
> = {
  implements: "implemented-by",
  satisfies: "satisfied-by",
  tests: "tested-by",
  verifies: "verified-by",
  documents: "documented-by",
  depends: "depended-by",
  requires: "required-by",
  addresses: "addressed-by",
  "composed-of": "part-of",
  "depends-on": "is-a-dependency-of",
  refines: "refined-by",
  "leads-to": "led-by",
};

export const PRIMARY_MAP: Record<
  InverseRelationshipType,
  PrimaryRelationshipType
> = {
  "implemented-by": "implements",
  "satisfied-by": "satisfies",
  "tested-by": "tests",
  "verified-by": "verifies",
  "documented-by": "documents",
  "depended-by": "depends",
  "required-by": "requires",
  "addressed-by": "addresses",
  "part-of": "composed-of",
  "is-a-dependency-of": "depends-on",
  "refined-by": "refines",
  "led-by": "leads-to",
} as const;

// ============================================================================
// Coverage and Matrix Types
// ============================================================================

/**
 * Coverage report for traceability analysis
 */
export interface CoverageReport {
  totalRequirements: number;
  requirementsWithImplementation: number;
  requirementsWithTests: number;
  implementationCoverage: number;
  testCoverage: number;
  // Design coverage metrics
  totalDesigns?: number;
  designsWithImplementation?: number;
  designCoverage?: number;
  requirementsAddressedByDesign?: number;
  requirementCoverageByDesign?: number;
}

/**
 * Row data for requirement matrices
 */
export interface RequirementRow {
  id: string;
  title: string;
  implementations: string[];
  tests: string[];
}

/**
 * Row data for design matrices
 */
export interface DesignRow {
  id: string;
  title: string;
  implementations: string[];
  tests: string[];
  depth?: number;
}

/**
 * Detailed requirement information
 */
export interface RequirementDetail {
  id: string;
  title: string;
  status: string;
  satisfiedBy: string[];
  implementedBy: string[];
  testedBy: string[];
  verifiedBy: string[];
  documentedBy: string[];
}

/**
 * Detailed implementation information
 */
export interface ImplementationDetail {
  id: string;
  title: string;
  satisfies: string[];
  testedBy: string[];
}

/**
 * Detailed test information
 */
export interface TestDetail {
  id: string;
  title: string;
  verifies: string[];
  tests: string[];
}

/**
 * Traceability matrix data structure
 */
export interface TraceabilityMatrix {
  type: string;
  coverage: CoverageReport;
  requirements: RequirementRow[];
  generatedAt: string;
}

/**
 * Design traceability matrix data structure
 */
export interface DesignTraceabilityMatrix {
  type: string;
  coverage: CoverageReport;
  designs: DesignRow[];
  generatedAt: string;
}

/**
 * Detailed traceability matrix with all information
 */
export interface DetailedTraceabilityMatrix {
  type: string;
  coverage: CoverageReport;
  uncoveredRequirements: string[];
  requirements: RequirementDetail[];
  implementations: ImplementationDetail[];
  tests: TestDetail[];
  generatedAt: string;
}

// ============================================================================
// Type Guards
// ============================================================================

/**
 * Check if a relationship type is primary
 */
export function isPrimaryRelationshipType(
  type: string,
): type is PrimaryRelationshipType {
  return type in INVERSE_MAP;
}

/**
 * Check if a relationship type is inverse
 */
export function isInverseRelationshipType(
  type: string,
): type is InverseRelationshipType {
  return type in PRIMARY_MAP;
}

/**
 * Check if a node is a Requirement
 */
export function isRequirement(node: AnyNode): node is Requirement {
  return "satisfiedBy" in node;
}

/**
 * Check if a node is an Implementation
 */
export function isImplementation(node: AnyNode): node is Implementation {
  return "satisfies" in node && "testedBy" in node;
}

/**
 * Check if a node is a Test
 */
export function isTest(node: AnyNode): node is Test {
  return "verifies" in node || "tests" in node;
}

/**
 * Check if a node is a Document
 */
export function isDocument(node: AnyNode): node is Document {
  return "documentedBy" in node || "documents" in node;
}

/**
 * Check if a node is a Design
 */
export function isDesign(node: AnyNode): node is Design {
  return (
    !("satisfiedBy" in node) &&
    !("satisfies" in node) &&
    !("verifies" in node) &&
    !("tests" in node)
  );
}

// ============================================================================
// Processing Options
// ============================================================================

/**
 * Options for processing AsciiDoc content
 */
export interface ProcessOptions {
  sourceFile?: string;
  configPath?: string; // Path to traceability configuration
}

// ============================================================================
// Types
// ============================================================================

/**
 * Traceability configuration reference (for passing to processors)
 */
export interface TraceabilityConfigRef {
  roles: string[];
  relations?: Record<string, Record<string, string[]>>;
  matrices?: any[];
}

/**
 * Parse result for unified parser
 */
export interface ParseResult {
  items: Item[];
  relationships: ItemRelationship[];
}

/**
 * Matrix generation options
 */
export interface MatrixGeneratorOptions {
  templateDir?: string;
  config?: TraceabilityConfigRef;
}
