/**
 * Type definitions for unified item architecture
 * This file contains the types for requirements traceability
 */

// ============================================================================
// Core Item Type
// ============================================================================

/**
 * Base type for all traceable items
 */
export interface Item {
  id: string;
  title: string;
  content?: string;
  role: string; // User-defined role (requirement, design, test, etc.)
  status?: string;
  attributes: Record<string, string>;
  sourceFile?: string;
  sourceLine?: number;
  /** Antora component name (e.g., "tracer"). Absent for CLI usage. */
  component?: string;
  /** Antora module name (e.g., "ROOT", "requirements"). Absent for CLI usage. */
  module?: string;
}

/**
 * Relationship between items with role information
 */
export interface ItemRelationship {
  id: string;
  fromId: string;
  targetId: string;
  type: string; // User-defined relation type
  sourceFile?: string;
  line?: number;
  autoGenerated?: boolean;
  inverseOf?: string;
  bidirectional?: boolean;
}

// ============================================================================
// Role Colors
// ============================================================================

/**
 * Role → GraphViz color mapping.
 * Shared by the data graph (`TraceabilityGraph.toDot`) and the configuration
 * graph (`toConfigDot`) so role colors stay consistent across both diagrams.
 */
export const ROLE_COLORS: Record<string, string> = {
  requirement: "#4A90D9",
  design: "#50B86C",
  architecture: "#50B86C",
  implementation: "#E8A838",
  test: "#D94A4A",
  document: "#8E6ECF",
};

// ============================================================================
// Coverage and Matrix Types
// ============================================================================

/**
 * Coverage report for traceability analysis
 */
export interface CoverageReport {
  totalRequirements: number;
  requirementsWithImplementation: number;
  requirementsWithTests: number;
  implementationCoverage: number;
  testCoverage: number;
  // Design coverage metrics
  totalDesigns?: number;
  designsWithImplementation?: number;
  designCoverage?: number;
  requirementsAddressedByDesign?: number;
  requirementCoverageByDesign?: number;
}

/**
 * Row data for requirement matrices
 */
export interface RequirementRow {
  id: string;
  title: string;
  implementations: string[];
  tests: string[];
}

/**
 * Row data for design matrices
 */
export interface DesignRow {
  id: string;
  title: string;
  implementations: string[];
  tests: string[];
  depth?: number;
}

/**
 * Detailed requirement information
 */
export interface RequirementDetail {
  id: string;
  title: string;
  status: string;
  satisfiedBy: string[];
  implementedBy: string[];
  testedBy: string[];
  verifiedBy: string[];
  documentedBy: string[];
}

/**
 * Detailed implementation information
 */
export interface ImplementationDetail {
  id: string;
  title: string;
  satisfies: string[];
  testedBy: string[];
}

/**
 * Detailed test information
 */
export interface TestDetail {
  id: string;
  title: string;
  verifies: string[];
  tests: string[];
}

/**
 * Traceability matrix data structure
 */
export interface TraceabilityMatrix {
  type: string;
  coverage: CoverageReport;
  requirements: RequirementRow[];
  generatedAt: string;
}

/**
 * Design traceability matrix data structure
 */
export interface DesignTraceabilityMatrix {
  type: string;
  coverage: CoverageReport;
  designs: DesignRow[];
  generatedAt: string;
}

/**
 * Detailed traceability matrix with all information
 */
export interface DetailedTraceabilityMatrix {
  type: string;
  coverage: CoverageReport;
  uncoveredRequirements: string[];
  requirements: RequirementDetail[];
  implementations: ImplementationDetail[];
  tests: TestDetail[];
  generatedAt: string;
}

// ============================================================================
// Processing Options
// ============================================================================

/**
 * Options for processing AsciiDoc content
 */
export interface ProcessOptions {
  sourceFile?: string;
  configPath?: string; // Path to traceability configuration
}

// ============================================================================
// Types
// ============================================================================

/**
 * Traceability configuration reference (for passing to processors)
 */
export interface TraceabilityConfigRef {
  roles: string[];
  relations?: Record<
    string,
    Record<string, Record<string, { reverse: string }>>
  >;
  matrices?: any[];
}

/**
 * Parse result for unified parser
 */
export interface ParseResult {
  items: Item[];
  relationships: ItemRelationship[];
}

/**
 * Matrix generation options
 */
export interface MatrixGeneratorOptions {
  templateDir?: string;
  config?: TraceabilityConfigRef;
}
